// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReportRecordList struct {
	Records              []*ReportRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReportRecordList) Reset()         { *m = ReportRecordList{} }
func (m *ReportRecordList) String() string { return proto.CompactTextString(m) }
func (*ReportRecordList) ProtoMessage()    {}
func (*ReportRecordList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{0}
}

func (m *ReportRecordList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRecordList.Unmarshal(m, b)
}
func (m *ReportRecordList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRecordList.Marshal(b, m, deterministic)
}
func (m *ReportRecordList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRecordList.Merge(m, src)
}
func (m *ReportRecordList) XXX_Size() int {
	return xxx_messageInfo_ReportRecordList.Size(m)
}
func (m *ReportRecordList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRecordList.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRecordList proto.InternalMessageInfo

func (m *ReportRecordList) GetRecords() []*ReportRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ReportRecord struct {
	EventAction          string            `protobuf:"bytes,1,opt,name=event_action,json=eventAction,proto3" json:"event_action,omitempty"`
	CommonData           map[string]string `protobuf:"bytes,2,rep,name=common_data,json=commonData,proto3" json:"common_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BizData              map[string]string `protobuf:"bytes,3,rep,name=biz_data,json=bizData,proto3" json:"biz_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReportRecord) Reset()         { *m = ReportRecord{} }
func (m *ReportRecord) String() string { return proto.CompactTextString(m) }
func (*ReportRecord) ProtoMessage()    {}
func (*ReportRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{1}
}

func (m *ReportRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRecord.Unmarshal(m, b)
}
func (m *ReportRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRecord.Marshal(b, m, deterministic)
}
func (m *ReportRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRecord.Merge(m, src)
}
func (m *ReportRecord) XXX_Size() int {
	return xxx_messageInfo_ReportRecord.Size(m)
}
func (m *ReportRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRecord proto.InternalMessageInfo

func (m *ReportRecord) GetEventAction() string {
	if m != nil {
		return m.EventAction
	}
	return ""
}

func (m *ReportRecord) GetCommonData() map[string]string {
	if m != nil {
		return m.CommonData
	}
	return nil
}

func (m *ReportRecord) GetBizData() map[string]string {
	if m != nil {
		return m.BizData
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportRecordList)(nil), "msg.ReportRecordList")
	proto.RegisterType((*ReportRecord)(nil), "msg.ReportRecord")
	proto.RegisterMapType((map[string]string)(nil), "msg.ReportRecord.BizDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "msg.ReportRecord.CommonDataEntry")
}

func init() { proto.RegisterFile("report.proto", fileDescriptor_3eedb623aa6ca98c) }

var fileDescriptor_3eedb623aa6ca98c = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xb2, 0xe7,
	0x12, 0x08, 0x02, 0x0b, 0x06, 0xa5, 0x26, 0xe7, 0x17, 0xa5, 0xf8, 0x64, 0x16, 0x97, 0x08, 0x69,
	0x73, 0xb1, 0x17, 0x81, 0x79, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x82, 0x7a, 0xb9,
	0xc5, 0xe9, 0x7a, 0xc8, 0xea, 0x82, 0x60, 0x2a, 0x94, 0x56, 0x33, 0x71, 0xf1, 0x20, 0xcb, 0x08,
	0x29, 0x72, 0xf1, 0xa4, 0x96, 0xa5, 0xe6, 0x95, 0xc4, 0x27, 0x26, 0x97, 0x64, 0xe6, 0xe7, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x83, 0xc5, 0x1c, 0xc1, 0x42, 0x42, 0x4e, 0x5c, 0xdc,
	0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0xf1, 0x29, 0x89, 0x25, 0x89, 0x12, 0x4c, 0x60, 0x4b, 0x14,
	0x31, 0x2c, 0xd1, 0x73, 0x06, 0x2b, 0x72, 0x49, 0x2c, 0x49, 0x74, 0xcd, 0x2b, 0x29, 0xaa, 0x0c,
	0xe2, 0x4a, 0x86, 0x0b, 0x08, 0x59, 0x72, 0x71, 0x24, 0x65, 0x56, 0x41, 0x0c, 0x60, 0x06, 0x1b,
	0x20, 0x87, 0x69, 0x80, 0x53, 0x66, 0x15, 0x42, 0x37, 0x7b, 0x12, 0x84, 0x27, 0x65, 0xcb, 0xc5,
	0x8f, 0x66, 0xb2, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0xd4, 0xad, 0x20, 0xa6, 0x90, 0x08,
	0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13, 0x58, 0x0c, 0xc2, 0xb1, 0x62, 0xb2, 0x60,
	0x94, 0xb2, 0xe2, 0xe2, 0x41, 0x36, 0x97, 0x14, 0xbd, 0x49, 0x6c, 0xe0, 0xa0, 0x37, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0x91, 0xd6, 0xb0, 0x8a, 0x01, 0x00, 0x00,
}
